### ISSUE TITLE
Code removed?

### ISSUE THREAD

**Issue by StuckinPhD** [fabianbalsiger/point-cloud-segmentation-miccai2019#1]
Hi, 

In your paper you mentioned that the code is made publicly available for reproducibility but you seem to have removed the code for some reason.

Can you please upload it again, or kindly share why it was removed?

Thank you

**Comment by DLwbm123** [comment]
Same question to me!

**Comment by fabianbalsiger** [comment]
Dear @StuckinPhD and @DLwbm123 

Sorry for the late response, I somehow didn't get notified about your issues.
I just released the code. I hope this helps. Please reopen if you have any questions.

Greetings,
Fabian
